// components/home/expertise.tsx
import {
  IconType as ReactSimpleIcon,
  SiFigma,
  SiJavascript,
  SiNextdotjs,
  SiReact,
  SiTypescript,
} from "@icons-pack/react-simple-icons";

type Props = React.HTMLAttributes<HTMLElement>;

export function Expertise(props: Props) {
  return (
    <section {...props}>
      <div className="grid max-w-xl grid-cols-2 gap-3 xs:grid-cols-3 sm:gap-4 lg:max-w-2xl lg:gap-6">
        {skills.map(({ icon, text }, index) => (
          <Skill key={index} icon={icon} text={text} />
        ))}
      </div>
    </section>
  );
}

type SkillItem = {
  icon: ReactSimpleIcon;
  text: string;
};

const skills: SkillItem[] = [
  { icon: SiNextdotjs, text: "Next.js" },
  { icon: SiReact, text: "React.js" },
  { icon: SiTypescript, text: "TypeScript" },
  { icon: SiJavascript, text: "JavaScript" },
  { icon: SiFigma, text: "Figma" },
];

type SkillProps = SkillItem;

function Skill({ icon: Icon, text }: SkillProps) {
  return (
    <div className="flex items-center gap-x-2 sm:gap-x-3 lg:gap-x-4">
      <span className="inline-block">
        <Icon className="size-4 sm:size-6 lg:size-7" color="default" />
      </span>
      <span className="text-base tracking-wide sm:text-lg lg:text-xl">
        {text}
      </span>
    </div>
  );
}

// src/lib/components/home/Expertise.svelte
<script lang="ts">
  import Icon from "$lib/components/Icon.svelte";
  import type { IconName } from "$lib/types/icons";

  interface SkillItem {
    icon: IconName;
    text: string;
    color?: string;
  }

  const skills: SkillItem[] = [
    {
      icon: "nextjs",
      text: "Next.js",
      color: "#000000",
    },
    {
      icon: "react",
      text: "React.js",
      color: "#61DAFB",
    },
    {
      icon: "typescript",
      text: "TypeScript",
      color: "#3178C6",
    },
    {
      icon: "javascript",
      text: "JavaScript",
      color: "#F7DF1E",
    },
    {
      icon: "figma",
      text: "Figma",
      color: "#F24E1E",
    },
  ];
</script>

<section>
  <div
    class="grid max-w-xl grid-cols-2 gap-3 xs:grid-cols-3 sm:gap-4 lg:max-w-2xl lg:gap-6"
  >
    {#each skills as { icon, text, color }}
      <div class="flex items-center gap-x-2 sm:gap-x-3 lg:gap-x-4">
        <Icon name={icon} class="size-4 sm:size-6 lg:size-7" {color} />
        <span class="text-base tracking-wide sm:text-lg lg:text-xl">
          {text}
        </span>
      </div>
    {/each}
  </div>
</section>
