// components/home/profession-intro.tsx
type Props = React.HTMLAttributes<HTMLElement>;

export function ProfessionIntro(props: Props) {
  return (
    <section {...props}>
      <h4 className="font-display text-xl font-bold uppercase leading-none tracking-widest sm:text-3xl sm:leading-none lg:text-5xl lg:leading-none">
        Frontend Engineer
      </h4>
      <p className="mt-0.5 space-x-1.5 text-sm italic tracking-wide sm:text-base lg:mt-1.5 lg:text-xl">
        <span className="text-muted-foreground">from</span>
        <span>Punjab, India</span>
      </p>
    </section>
  );
}

// src/lib/components/home/ProfessionIntro.svelte
<section>
	<h2 class="font-display text-2xl font-bold uppercase leading-none tracking-widest sm:text-3xl sm:leading-none lg:text-4xl lg:leading-none">
		Frontend Engineer
	</h2>
	<p class="mt-2 space-x-1.5 text-sm italic tracking-wide sm:text-base lg:text-lg">
		<span class="text-muted-foreground">from</span>
		<span>Punjab, India</span>
	</p>
</section>
