// src/lib/components/TailwindIndicator.svelte
<script lang="ts">
	import { dev } from '$app/environment';
</script>

{#if dev}
	<div class="fixed bottom-1 left-1 z-50 flex h-6 w-6 items-center justify-center rounded-full bg-gray-800 p-3 font-mono text-xs text-white">
		<div class="block xs:hidden">xxs</div>
		<div class="hidden xs:block sm:hidden md:hidden lg:hidden xl:hidden 2xl:hidden">
			xs
		</div>
		<div class="hidden sm:block md:hidden lg:hidden xl:hidden 2xl:hidden">
			sm
		</div>
		<div class="hidden md:block lg:hidden xl:hidden 2xl:hidden">md</div>
		<div class="hidden lg:block xl:hidden 2xl:hidden">lg</div>
		<div class="hidden xl:block 2xl:hidden">xl</div>
		<div class="hidden 2xl:block">2xl</div>
	</div>
{/if}

// components/tailwind-indicator.tsx
export function TailwindIndicator() {
  if (process.env.NODE_ENV === "production") return null;

  return (
    <div className="fixed bottom-1 left-1 z-50 flex h-6 w-6 items-center justify-center rounded-full bg-gray-800 p-3 font-mono text-xs text-white">
      <div className="block xs:hidden">xxs</div>
      <div className="hidden xs:block sm:hidden md:hidden lg:hidden xl:hidden 2xl:hidden">
        xs
      </div>
      <div className="hidden sm:block md:hidden lg:hidden xl:hidden 2xl:hidden">
        sm
      </div>
      <div className="hidden md:block lg:hidden xl:hidden 2xl:hidden">md</div>
      <div className="hidden lg:block xl:hidden 2xl:hidden">lg</div>
      <div className="hidden xl:block 2xl:hidden">xl</div>
      <div className="hidden 2xl:block">2xl</div>
    </div>
  );
}
