// components/work/project-details.tsx
import type { PropsWithChildren } from "react";
import Link from "next/link";
import { ExternalLinkIcon } from "@radix-ui/react-icons";

type Props = PropsWithChildren<{
  title: string;
  description: string;
  link?: string;
}>;

export function ProjectDetails({ title, description, link, children }: Props) {
  return (
    <article>
      <div className="group inline-flex items-baseline gap-x-2">
        <h2 className="-ml-px font-display text-xl font-normal uppercase leading-none tracking-widest sm:text-3xl sm:leading-none lg:text-4xl lg:leading-none">
          {title}
        </h2>
        {link && (
          <Link href={link} target="_blank">
            <ExternalLinkIcon className="size-5 text-muted-foreground group-hover:text-foreground" />
          </Link>
        )}
      </div>
      <div className="mt-2 max-w-xl text-base leading-relaxed tracking-wide sm:mt-3 sm:text-lg sm:leading-relaxed lg:max-w-2xl lg:text-xl lg:leading-relaxed">
        {description}
      </div>
      {children}
    </article>
  );
}

// src/lib/components/work/ProjectDetails.svelte
<!-- 
  ProjectDetails.svelte
  Migrated from components/work/project-details.tsx
  Displays project title, description, and external link with children content
-->

<script lang="ts">
	let { title, description, link = undefined }: { 
		title: string; 
		description: string; 
		link?: string | undefined 
	} = $props();
</script>

<article>
	<div class="group inline-flex items-baseline gap-x-2">
		<h2 
			class="-ml-px font-display text-xl font-normal uppercase leading-none tracking-widest sm:text-3xl sm:leading-none lg:text-4xl lg:leading-none"
		>
			{title}
		</h2>
		{#if link}
			<a href={link} target="_blank" rel="noopener noreferrer">
				<!-- External Link Icon (from @radix-ui/react-icons) -->
				<svg
					class="size-5 text-muted-foreground group-hover:text-foreground"
					width="15"
					height="15"
					viewBox="0 0 15 15"
					fill="none"
					xmlns="http://www.w3.org/2000/svg"
				>
					<path
						d="M3 2C2.44772 2 2 2.44772 2 3V12C2 12.5523 2.44772 13 3 13H12C12.5523 13 13 12.5523 13 12V8.5C13 8.22386 12.7761 8 12.5 8C12.2239 8 12 8.22386 12 8.5V12H3V3L6.5 3C6.77614 3 7 2.77614 7 2.5C7 2.22386 6.77614 2 6.5 2H3ZM12.8536 2.14645C12.9015 2.19439 12.9377 2.24964 12.9621 2.30861C12.9861 2.36669 12.9996 2.4303 13 2.497L13 2.5V2.50049V5.5C13 5.77614 12.7761 6 12.5 6C12.2239 6 12 5.77614 12 5.5V3.70711L6.85355 8.85355C6.65829 9.04882 6.34171 9.04882 6.14645 8.85355C5.95118 8.65829 5.95118 8.34171 6.14645 8.14645L11.2929 3H9.5C9.22386 3 9 2.77614 9 2.5C9 2.22386 9.22386 2 9.5 2H12.4999H12.5C12.5678 2 12.6324 2.01349 12.6914 2.03794C12.7504 2.06234 12.8056 2.09851 12.8536 2.14645Z"
						fill="currentColor"
						fill-rule="evenodd"
						clip-rule="evenodd"
					/>
				</svg>
			</a>
		{/if}
	</div>
	<div 
		class="mt-2 max-w-xl text-base leading-relaxed tracking-wide sm:mt-3 sm:text-lg sm:leading-relaxed lg:max-w-2xl lg:text-xl lg:leading-relaxed"
	>
		{description}
	</div>
	<slot />
</article>
