// components/fade-in-section.tsx
"use client";

import React, { useEffect, useRef, useState } from "react";

interface FadeInSectionProps {
  children: React.ReactNode;
}

export function FadeInSection({ children }: FadeInSectionProps) {
  const [isVisible, setVisible] = useState(false);
  const domRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => setVisible(entry.isIntersecting));
    });

    const currentElement = domRef.current;
    if (currentElement) {
      observer.observe(currentElement);
    }

    return () => {
      if (currentElement) {
        observer.unobserve(currentElement);
      }
    };
  }, []);

  return (
    <div
      className={`section-fade-in ${isVisible ? "visible" : ""}`}
      ref={domRef}
    >
      {children}
    </div>
  );
}

// src/lib/components/FadeInSection.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	interface Props {
		children: import('svelte').Snippet;
	}

	let { children }: Props = $props();
	let isVisible = $state(false);
	let domRef: HTMLDivElement;

	onMount(() => {
		const observer = new IntersectionObserver((entries) => {
			entries.forEach((entry) => isVisible = entry.isIntersecting);
		});

		if (domRef) {
			observer.observe(domRef);
		}

		return () => {
			if (domRef) {
				observer.unobserve(domRef);
			}
		};
	});
</script>

<div
	bind:this={domRef}
	class={`section-fade-in ${isVisible ? "visible" : ""}`}
>
	{@render children()}
</div>
